name: Deploy on Push

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Test SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no lanternfudextech@65.21.247.82 'echo "SSH connection successful!"'
        
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no lanternfudextech@65.21.247.82 'cd /home/lanternfudextech/public_html/backend.lantern.fudex-tech.net && git pull origin main && echo "Deployment completed successfully." || echo "Deployment failed."'

    - name: Run Migrations
      run: |
        ssh -o StrictHostKeyChecking=no lanternfudextech@65.21.247.82 'cd /home/lanternfudextech/public_html/backend.lantern.fudex-tech.net && php artisan migrate --force'